dependencies:
    - python=3.9
    - pip>=19.0
    - jupyter
    - apple::tensorflow-deps==2.5.0
    - scikit-learn
    - scipy
    - numpy
    - pandas
    - pandas-datareader
    - matplotlib
    - pillow
    - tqdm
    - requests
    - h5py
    - pyyaml
    - flask
    - boto3