training_pipeline_config:
  pipeline_name: src
  artifact_dir : artifact

data_ingestion_config:
  data_source_url : "https://www.dropbox.com/s/u6xndpb3t8rhmv1/Chest_XRay_Data.zip?dl=1"
  local_zip_data_dir : ziped_data
  local_raw_data_dir : raw_data
  local_ingested_csv_data_dir : ingested_csv_data
  local_train_csv_data_dir : train_csv_data
  local_test_csv_data_dir : test_csv_data
  local_val_csv_data_dir : val_csv_data

data_validation_config:
  schema_file_dir: config
  schema_file_name: schema.yml
  local_validation_reports_dir: validation_reports

data_transformation_config:
  transformed_data_dir: transformed_data
  transformed_train_data_dir: train
  transformed_test_data_dir: test
  transformed_val_data_dir: val

  








  



  